name: PoisonPopTart  
  
on:  
  pull_request_target:  
  
jobs:  
  CheckoutPopTart:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout branch  
        uses: actions/checkout@v3  
        with:  
          token: ${{ secrets.CD_PAT }}  
          ref: ${{ github.event.pull_request.head.ref }}  
            
      - name: Setup node  
        uses: actions/setup-node@v3  
        with:  
          node-version: 14  
            
      - name: Setup project  
        id: setup  
        run: npm run setup  
        continue-on-error: true  
          
      - name: Info  
        if: steps.setup.outcome != 'success'  
        run: |  
          echo "`npm run setup` failed after current project finish CD, \  
          it may be the inconsistency of package dependencies caused by separate release, \  
          please confirm this problem will not affect the CI of subsequent PRs." 
